/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Chain model module.
 * @module model/Chain
 * @version 1.0
 */
class Chain {
    /**
     * Constructs a new <code>Chain</code>.
     * @alias module:model/Chain
     */
    constructor() { 
        
        Chain.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Chain</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Chain} obj Optional instance to populate.
     * @return {module:model/Chain} The populated <code>Chain</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Chain();

            if (data.hasOwnProperty('confirm_num')) {
                obj['confirm_num'] = ApiClient.convertToType(data['confirm_num'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('explorer_address_url')) {
                obj['explorer_address_url'] = ApiClient.convertToType(data['explorer_address_url'], 'String');
            }
            if (data.hasOwnProperty('explorer_block_url')) {
                obj['explorer_block_url'] = ApiClient.convertToType(data['explorer_block_url'], 'String');
            }
            if (data.hasOwnProperty('explorer_tx_url')) {
                obj['explorer_tx_url'] = ApiClient.convertToType(data['explorer_tx_url'], 'String');
            }
            if (data.hasOwnProperty('icon_url')) {
                obj['icon_url'] = ApiClient.convertToType(data['icon_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('need_memo')) {
                obj['need_memo'] = ApiClient.convertToType(data['need_memo'], 'Boolean');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Chain</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Chain</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['explorer_address_url'] && !(typeof data['explorer_address_url'] === 'string' || data['explorer_address_url'] instanceof String)) {
            throw new Error("Expected the field `explorer_address_url` to be a primitive type in the JSON string but got " + data['explorer_address_url']);
        }
        // ensure the json data is a string
        if (data['explorer_block_url'] && !(typeof data['explorer_block_url'] === 'string' || data['explorer_block_url'] instanceof String)) {
            throw new Error("Expected the field `explorer_block_url` to be a primitive type in the JSON string but got " + data['explorer_block_url']);
        }
        // ensure the json data is a string
        if (data['explorer_tx_url'] && !(typeof data['explorer_tx_url'] === 'string' || data['explorer_tx_url'] instanceof String)) {
            throw new Error("Expected the field `explorer_tx_url` to be a primitive type in the JSON string but got " + data['explorer_tx_url']);
        }
        // ensure the json data is a string
        if (data['icon_url'] && !(typeof data['icon_url'] === 'string' || data['icon_url'] instanceof String)) {
            throw new Error("Expected the field `icon_url` to be a primitive type in the JSON string but got " + data['icon_url']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}



/**
 * Confirmation number
 * @member {Number} confirm_num
 */
Chain.prototype['confirm_num'] = undefined;

/**
 * Created time
 * @member {String} created_at
 */
Chain.prototype['created_at'] = undefined;

/**
 * Explorer address URL
 * @member {String} explorer_address_url
 */
Chain.prototype['explorer_address_url'] = undefined;

/**
 * Explorer block URL
 * @member {String} explorer_block_url
 */
Chain.prototype['explorer_block_url'] = undefined;

/**
 * Explorer transaction URL
 * @member {String} explorer_tx_url
 */
Chain.prototype['explorer_tx_url'] = undefined;

/**
 * Icon URL
 * @member {String} icon_url
 */
Chain.prototype['icon_url'] = undefined;

/**
 * Chain ID
 * @member {String} id
 */
Chain.prototype['id'] = undefined;

/**
 * Chain name
 * @member {String} name
 */
Chain.prototype['name'] = undefined;

/**
 * Need memo
 * @member {Boolean} need_memo
 */
Chain.prototype['need_memo'] = undefined;

/**
 * Chain symbol
 * @member {String} symbol
 */
Chain.prototype['symbol'] = undefined;

/**
 * Updated time
 * @member {String} updated_at
 */
Chain.prototype['updated_at'] = undefined;






export default Chain;

