/**
 * WaaS OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateTransferResponse model module.
 * @module model/CreateTransferResponse
 * @version 1.0
 */
class CreateTransferResponse {
    /**
     * Constructs a new <code>CreateTransferResponse</code>.
     * @alias module:model/CreateTransferResponse
     * @param transactionId {String} Transaction ID
     */
    constructor(transactionId) { 
        
        CreateTransferResponse.initialize(this, transactionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transactionId) { 
        obj['transaction_id'] = transactionId;
    }

    /**
     * Constructs a <code>CreateTransferResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTransferResponse} obj Optional instance to populate.
     * @return {module:model/CreateTransferResponse} The populated <code>CreateTransferResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTransferResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('transaction_id')) {
                obj['transaction_id'] = ApiClient.convertToType(data['transaction_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Transaction status
 * @member {String} status
 */
CreateTransferResponse.prototype['status'] = undefined;

/**
 * Transaction ID
 * @member {String} transaction_id
 */
CreateTransferResponse.prototype['transaction_id'] = undefined;






export default CreateTransferResponse;

