/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransferSourceAsset from './TransferSourceAsset';

/**
 * The CreateTransferRequestSource model module.
 * @module model/CreateTransferRequestSource
 * @version 1.0
 */
class CreateTransferRequestSource {
    /**
     * Constructs a new <code>CreateTransferRequestSource</code>.
     * The ID of the wallet from which the transfer will be made
     * @alias module:model/CreateTransferRequestSource
     * @param {(module:model/TransferSourceAsset)} instance The actual instance to initialize CreateTransferRequestSource.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "TransferSourceAsset") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                TransferSourceAsset.validateJSON(instance); // throw an exception if no match
                // create TransferSourceAsset from JS object
                this.actualInstance = TransferSourceAsset.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TransferSourceAsset
            errorMessages.push("Failed to construct TransferSourceAsset: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `CreateTransferRequestSource` with oneOf schemas TransferSourceAsset. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `CreateTransferRequestSource` with oneOf schemas TransferSourceAsset. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>CreateTransferRequestSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTransferRequestSource} obj Optional instance to populate.
     * @return {module:model/CreateTransferRequestSource} The populated <code>CreateTransferRequestSource</code> instance.
     */
    static constructFromObject(data, obj) {
        return new CreateTransferRequestSource(data);
    }

    /**
     * Gets the actual instance, which can be <code>TransferSourceAsset</code>.
     * @return {(module:model/TransferSourceAsset)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>TransferSourceAsset</code>.
     * @param {(module:model/TransferSourceAsset)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = CreateTransferRequestSource.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of CreateTransferRequestSource from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/CreateTransferRequestSource} An instance of CreateTransferRequestSource.
     */
    static fromJSON = function(json_string){
        return CreateTransferRequestSource.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * source type
 * @member {String} source_type
 */
CreateTransferRequestSource.prototype['source_type'] = undefined;

/**
 * Wallet ID
 * @member {String} wallet_id
 */
CreateTransferRequestSource.prototype['wallet_id'] = undefined;


CreateTransferRequestSource.OneOf = ["TransferSourceAsset"];

export default CreateTransferRequestSource;

