/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Endpoint from './Endpoint';

/**
 * The CursorIteratorEndpoint model module.
 * @module model/CursorIteratorEndpoint
 * @version 1.0
 */
class CursorIteratorEndpoint {
    /**
     * Constructs a new <code>CursorIteratorEndpoint</code>.
     * @alias module:model/CursorIteratorEndpoint
     * @param done {Boolean} 
     * @param hasNext {Boolean} 
     * @param hasPrev {Boolean} 
     * @param items {Array.<module:model/Endpoint>} 
     */
    constructor(done, hasNext, hasPrev, items) { 
        
        CursorIteratorEndpoint.initialize(this, done, hasNext, hasPrev, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, done, hasNext, hasPrev, items) { 
        obj['done'] = done;
        obj['has_next'] = hasNext;
        obj['has_prev'] = hasPrev;
        obj['items'] = items;
    }

    /**
     * Constructs a <code>CursorIteratorEndpoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CursorIteratorEndpoint} obj Optional instance to populate.
     * @return {module:model/CursorIteratorEndpoint} The populated <code>CursorIteratorEndpoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CursorIteratorEndpoint();

            if (data.hasOwnProperty('done')) {
                obj['done'] = ApiClient.convertToType(data['done'], 'Boolean');
            }
            if (data.hasOwnProperty('has_next')) {
                obj['has_next'] = ApiClient.convertToType(data['has_next'], 'Boolean');
            }
            if (data.hasOwnProperty('has_prev')) {
                obj['has_prev'] = ApiClient.convertToType(data['has_prev'], 'Boolean');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Endpoint]);
            }
            if (data.hasOwnProperty('next_cursor')) {
                obj['next_cursor'] = ApiClient.convertToType(data['next_cursor'], 'String');
            }
            if (data.hasOwnProperty('prev_cursor')) {
                obj['prev_cursor'] = ApiClient.convertToType(data['prev_cursor'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CursorIteratorEndpoint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CursorIteratorEndpoint</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CursorIteratorEndpoint.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                Endpoint.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['next_cursor'] && !(typeof data['next_cursor'] === 'string' || data['next_cursor'] instanceof String)) {
            throw new Error("Expected the field `next_cursor` to be a primitive type in the JSON string but got " + data['next_cursor']);
        }
        // ensure the json data is a string
        if (data['prev_cursor'] && !(typeof data['prev_cursor'] === 'string' || data['prev_cursor'] instanceof String)) {
            throw new Error("Expected the field `prev_cursor` to be a primitive type in the JSON string but got " + data['prev_cursor']);
        }

        return true;
    }


}

CursorIteratorEndpoint.RequiredProperties = ["done", "has_next", "has_prev", "items"];

/**
 * @member {Boolean} done
 */
CursorIteratorEndpoint.prototype['done'] = undefined;

/**
 * @member {Boolean} has_next
 */
CursorIteratorEndpoint.prototype['has_next'] = undefined;

/**
 * @member {Boolean} has_prev
 */
CursorIteratorEndpoint.prototype['has_prev'] = undefined;

/**
 * @member {Array.<module:model/Endpoint>} items
 */
CursorIteratorEndpoint.prototype['items'] = undefined;

/**
 * @member {String} next_cursor
 */
CursorIteratorEndpoint.prototype['next_cursor'] = undefined;

/**
 * @member {String} prev_cursor
 */
CursorIteratorEndpoint.prototype['prev_cursor'] = undefined;






export default CursorIteratorEndpoint;

