/**
 * WaaS OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Openweb3IoWaasAppWaasOpenapiServerApiDtosToken from './Openweb3IoWaasAppWaasOpenapiServerApiDtosToken';

/**
 * The CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken model module.
 * @module model/CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken
 * @version 1.0
 */
class CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken {
    /**
     * Constructs a new <code>CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken</code>.
     * @alias module:model/CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken
     * @param hasNext {Boolean} 
     * @param items {Array.<module:model/Openweb3IoWaasAppWaasOpenapiServerApiDtosToken>} 
     */
    constructor(hasNext, items) { 
        
        CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken.initialize(this, hasNext, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hasNext, items) { 
        obj['has_next'] = hasNext;
        obj['items'] = items;
    }

    /**
     * Constructs a <code>CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken} obj Optional instance to populate.
     * @return {module:model/CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken} The populated <code>CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken();

            if (data.hasOwnProperty('has_next')) {
                obj['has_next'] = ApiClient.convertToType(data['has_next'], 'Boolean');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Openweb3IoWaasAppWaasOpenapiServerApiDtosToken]);
            }
            if (data.hasOwnProperty('next_cursor')) {
                obj['next_cursor'] = ApiClient.convertToType(data['next_cursor'], 'String');
            }
            if (data.hasOwnProperty('prev_cursor')) {
                obj['prev_cursor'] = ApiClient.convertToType(data['prev_cursor'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} has_next
 */
CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken.prototype['has_next'] = undefined;

/**
 * @member {Array.<module:model/Openweb3IoWaasAppWaasOpenapiServerApiDtosToken>} items
 */
CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken.prototype['items'] = undefined;

/**
 * @member {String} next_cursor
 */
CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken.prototype['next_cursor'] = undefined;

/**
 * @member {String} prev_cursor
 */
CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken.prototype['prev_cursor'] = undefined;






export default CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosToken;

