/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EstimateFeeResponse model module.
 * @module model/EstimateFeeResponse
 * @version 1.0
 */
class EstimateFeeResponse {
    /**
     * Constructs a new <code>EstimateFeeResponse</code>.
     * @alias module:model/EstimateFeeResponse
     * @param amount {String} Amount
     * @param tokenId {String} Token ID
     */
    constructor(amount, tokenId) { 
        
        EstimateFeeResponse.initialize(this, amount, tokenId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, tokenId) { 
        obj['amount'] = amount;
        obj['token_id'] = tokenId;
    }

    /**
     * Constructs a <code>EstimateFeeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EstimateFeeResponse} obj Optional instance to populate.
     * @return {module:model/EstimateFeeResponse} The populated <code>EstimateFeeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EstimateFeeResponse();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EstimateFeeResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EstimateFeeResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EstimateFeeResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }

        return true;
    }


}

EstimateFeeResponse.RequiredProperties = ["amount", "token_id"];

/**
 * Amount
 * @member {String} amount
 */
EstimateFeeResponse.prototype['amount'] = undefined;

/**
 * Token ID
 * @member {String} token_id
 */
EstimateFeeResponse.prototype['token_id'] = undefined;






export default EstimateFeeResponse;

