/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Token model module.
 * @module model/Token
 * @version 1.0
 */
class Token {
    /**
     * Constructs a new <code>Token</code>.
     * @alias module:model/Token
     */
    constructor() { 
        
        Token.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Token</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Token} obj Optional instance to populate.
     * @return {module:model/Token} The populated <code>Token</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Token();

            if (data.hasOwnProperty('can_deposit')) {
                obj['can_deposit'] = ApiClient.convertToType(data['can_deposit'], 'Boolean');
            }
            if (data.hasOwnProperty('can_withdraw')) {
                obj['can_withdraw'] = ApiClient.convertToType(data['can_withdraw'], 'Boolean');
            }
            if (data.hasOwnProperty('contract_address')) {
                obj['contract_address'] = ApiClient.convertToType(data['contract_address'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('decimals')) {
                obj['decimals'] = ApiClient.convertToType(data['decimals'], 'Number');
            }
            if (data.hasOwnProperty('icon_url')) {
                obj['icon_url'] = ApiClient.convertToType(data['icon_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('max_withdraw_amount')) {
                obj['max_withdraw_amount'] = ApiClient.convertToType(data['max_withdraw_amount'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': 'String'});
            }
            if (data.hasOwnProperty('min_deposit_amount')) {
                obj['min_deposit_amount'] = ApiClient.convertToType(data['min_deposit_amount'], 'String');
            }
            if (data.hasOwnProperty('min_withdraw_amount')) {
                obj['min_withdraw_amount'] = ApiClient.convertToType(data['min_withdraw_amount'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('need_memo')) {
                obj['need_memo'] = ApiClient.convertToType(data['need_memo'], 'Boolean');
            }
            if (data.hasOwnProperty('precision')) {
                obj['precision'] = ApiClient.convertToType(data['precision'], 'Number');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('total_supply')) {
                obj['total_supply'] = ApiClient.convertToType(data['total_supply'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Token</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Token</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['contract_address'] && !(typeof data['contract_address'] === 'string' || data['contract_address'] instanceof String)) {
            throw new Error("Expected the field `contract_address` to be a primitive type in the JSON string but got " + data['contract_address']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['icon_url'] && !(typeof data['icon_url'] === 'string' || data['icon_url'] instanceof String)) {
            throw new Error("Expected the field `icon_url` to be a primitive type in the JSON string but got " + data['icon_url']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['max_withdraw_amount'] && !(typeof data['max_withdraw_amount'] === 'string' || data['max_withdraw_amount'] instanceof String)) {
            throw new Error("Expected the field `max_withdraw_amount` to be a primitive type in the JSON string but got " + data['max_withdraw_amount']);
        }
        // ensure the json data is a string
        if (data['min_deposit_amount'] && !(typeof data['min_deposit_amount'] === 'string' || data['min_deposit_amount'] instanceof String)) {
            throw new Error("Expected the field `min_deposit_amount` to be a primitive type in the JSON string but got " + data['min_deposit_amount']);
        }
        // ensure the json data is a string
        if (data['min_withdraw_amount'] && !(typeof data['min_withdraw_amount'] === 'string' || data['min_withdraw_amount'] instanceof String)) {
            throw new Error("Expected the field `min_withdraw_amount` to be a primitive type in the JSON string but got " + data['min_withdraw_amount']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }
        // ensure the json data is a string
        if (data['total_supply'] && !(typeof data['total_supply'] === 'string' || data['total_supply'] instanceof String)) {
            throw new Error("Expected the field `total_supply` to be a primitive type in the JSON string but got " + data['total_supply']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}



/**
 * Whether deposits are allowed
 * @member {Boolean} can_deposit
 */
Token.prototype['can_deposit'] = undefined;

/**
 * Whether withdrawals are allowed
 * @member {Boolean} can_withdraw
 */
Token.prototype['can_withdraw'] = undefined;

/**
 * Contract address
 * @member {String} contract_address
 */
Token.prototype['contract_address'] = undefined;

/**
 * Creation time
 * @member {String} created_at
 */
Token.prototype['created_at'] = undefined;

/**
 * Decimals
 * @member {Number} decimals
 */
Token.prototype['decimals'] = undefined;

/**
 * Icon
 * @member {String} icon_url
 */
Token.prototype['icon_url'] = undefined;

/**
 * Token ID
 * @member {String} id
 */
Token.prototype['id'] = undefined;

/**
 * Max withdraw amount
 * @member {String} max_withdraw_amount
 */
Token.prototype['max_withdraw_amount'] = undefined;

/**
 * Extended metadata
 * @member {Object.<String, String>} metadata
 */
Token.prototype['metadata'] = undefined;

/**
 * Min deposit amount
 * @member {String} min_deposit_amount
 */
Token.prototype['min_deposit_amount'] = undefined;

/**
 * Min withdraw amount
 * @member {String} min_withdraw_amount
 */
Token.prototype['min_withdraw_amount'] = undefined;

/**
 * Name
 * @member {String} name
 */
Token.prototype['name'] = undefined;

/**
 * Whether a memo is required
 * @member {Boolean} need_memo
 */
Token.prototype['need_memo'] = undefined;

/**
 * Precision
 * @member {Number} precision
 */
Token.prototype['precision'] = undefined;

/**
 * Symbol . e.g.: BTC / ETH
 * @member {String} symbol
 */
Token.prototype['symbol'] = undefined;

/**
 * Total supply
 * @member {String} total_supply
 */
Token.prototype['total_supply'] = undefined;

/**
 * Last updated time
 * @member {String} updated_at
 */
Token.prototype['updated_at'] = undefined;






export default Token;

