/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransferSourceAddress model module.
 * @module model/TransferSourceAddress
 * @version 1.0
 */
class TransferSourceAddress {
    /**
     * Constructs a new <code>TransferSourceAddress</code>.
     * @alias module:model/TransferSourceAddress
     * @param address {String} Address
     * @param walletId {String} Wallet ID
     */
    constructor(address, walletId) { 
        
        TransferSourceAddress.initialize(this, address, walletId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, walletId) { 
        obj['address'] = address;
        obj['wallet_id'] = walletId;
    }

    /**
     * Constructs a <code>TransferSourceAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransferSourceAddress} obj Optional instance to populate.
     * @return {module:model/TransferSourceAddress} The populated <code>TransferSourceAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransferSourceAddress();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('wallet_id')) {
                obj['wallet_id'] = ApiClient.convertToType(data['wallet_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransferSourceAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransferSourceAddress</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TransferSourceAddress.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['wallet_id'] && !(typeof data['wallet_id'] === 'string' || data['wallet_id'] instanceof String)) {
            throw new Error("Expected the field `wallet_id` to be a primitive type in the JSON string but got " + data['wallet_id']);
        }

        return true;
    }


}

TransferSourceAddress.RequiredProperties = ["address", "wallet_id"];

/**
 * Address
 * @member {String} address
 */
TransferSourceAddress.prototype['address'] = undefined;

/**
 * Wallet ID
 * @member {String} wallet_id
 */
TransferSourceAddress.prototype['wallet_id'] = undefined;






export default TransferSourceAddress;

