/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddressValidityItem from './AddressValidityItem';

/**
 * The ValidateAddressesReply model module.
 * @module model/ValidateAddressesReply
 * @version 1.0
 */
class ValidateAddressesReply {
    /**
     * Constructs a new <code>ValidateAddressesReply</code>.
     * @alias module:model/ValidateAddressesReply
     */
    constructor() { 
        
        ValidateAddressesReply.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidateAddressesReply</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidateAddressesReply} obj Optional instance to populate.
     * @return {module:model/ValidateAddressesReply} The populated <code>ValidateAddressesReply</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidateAddressesReply();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [AddressValidityItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidateAddressesReply</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidateAddressesReply</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                AddressValidityItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Address validity items
 * @member {Array.<module:model/AddressValidityItem>} items
 */
ValidateAddressesReply.prototype['items'] = undefined;






export default ValidateAddressesReply;

