/**
 * WaaS OpenAPI Documentation
 * This is a WaaS OpenAPI Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Wallet model module.
 * @module model/Wallet
 * @version 1.0
 */
class Wallet {
    /**
     * Constructs a new <code>Wallet</code>.
     * @alias module:model/Wallet
     * @param id {String} Wallet ID
     * @param name {String} Wallet name
     * @param uid {String} External unique ID
     */
    constructor(id, name, uid) { 
        
        Wallet.initialize(this, id, name, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, uid) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>Wallet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Wallet} obj Optional instance to populate.
     * @return {module:model/Wallet} The populated <code>Wallet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Wallet();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Created time
 * @member {String} created_at
 */
Wallet.prototype['created_at'] = undefined;

/**
 * Wallet ID
 * @member {String} id
 */
Wallet.prototype['id'] = undefined;

/**
 * Wallet name
 * @member {String} name
 */
Wallet.prototype['name'] = undefined;

/**
 * External unique ID
 * @member {String} uid
 */
Wallet.prototype['uid'] = undefined;

/**
 * Updated time
 * @member {String} updatedAt
 */
Wallet.prototype['updatedAt'] = undefined;






export default Wallet;

