/**
 * WaaS OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventType from './EventType';

/**
 * The Webhook model module.
 * @module model/Webhook
 * @version 1.0
 */
class Webhook {
    /**
     * Constructs a new <code>Webhook</code>.
     * @alias module:model/Webhook
     * @param createdAt {String} 
     * @param description {String} 
     * @param disabled {Boolean} 
     * @param eventTypes {Array.<module:model/EventType>} 
     * @param filter {String} 
     * @param headers {Object.<String, String>} 
     * @param id {String} 
     * @param metadata {Object.<String, Object>} 
     * @param url {String} 
     */
    constructor(createdAt, description, disabled, eventTypes, filter, headers, id, metadata, url) { 
        
        Webhook.initialize(this, createdAt, description, disabled, eventTypes, filter, headers, id, metadata, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, description, disabled, eventTypes, filter, headers, id, metadata, url) { 
        obj['createdAt'] = createdAt;
        obj['description'] = description;
        obj['disabled'] = disabled;
        obj['eventTypes'] = eventTypes;
        obj['filter'] = filter;
        obj['headers'] = headers;
        obj['id'] = id;
        obj['metadata'] = metadata;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>Webhook</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Webhook} obj Optional instance to populate.
     * @return {module:model/Webhook} The populated <code>Webhook</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Webhook();

            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('eventTypes')) {
                obj['eventTypes'] = ApiClient.convertToType(data['eventTypes'], [EventType]);
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], 'String');
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], {'String': 'String'});
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': Object});
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} createdAt
 */
Webhook.prototype['createdAt'] = undefined;

/**
 * @member {String} description
 */
Webhook.prototype['description'] = undefined;

/**
 * @member {Boolean} disabled
 */
Webhook.prototype['disabled'] = undefined;

/**
 * @member {Array.<module:model/EventType>} eventTypes
 */
Webhook.prototype['eventTypes'] = undefined;

/**
 * @member {String} filter
 */
Webhook.prototype['filter'] = undefined;

/**
 * @member {Object.<String, String>} headers
 */
Webhook.prototype['headers'] = undefined;

/**
 * @member {String} id
 */
Webhook.prototype['id'] = undefined;

/**
 * @member {Object.<String, Object>} metadata
 */
Webhook.prototype['metadata'] = undefined;

/**
 * @member {String} uid
 */
Webhook.prototype['uid'] = undefined;

/**
 * @member {String} url
 */
Webhook.prototype['url'] = undefined;






export default Webhook;

