/*
 * WaaS OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Openweb3IoWaasAppWaasOpenapiServerApiDtosFeeType
 */
public class Openweb3IoWaasAppWaasOpenapiServerApiDtosFeeTypeTest {
    /**
     * Model tests for Openweb3IoWaasAppWaasOpenapiServerApiDtosFeeType
     */
    @Test
    public void testOpenweb3IoWaasAppWaasOpenapiServerApiDtosFeeType() {
        // TODO: test Openweb3IoWaasAppWaasOpenapiServerApiDtosFeeType
    }

}
