/**
 * WaaS OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaaSOpenApiDocumentation);
  }
}(this, function(expect, WaaSOpenApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaaSOpenApiDocumentation.WebhookEndpointsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WebhookEndpointsApi', function() {
    describe('v1WebhooksCreate', function() {
      it('should call v1WebhooksCreate successfully', function(done) {
        //uncomment below and update the code to test v1WebhooksCreate
        //instance.v1WebhooksCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1WebhooksDelete', function() {
      it('should call v1WebhooksDelete successfully', function(done) {
        //uncomment below and update the code to test v1WebhooksDelete
        //instance.v1WebhooksDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1WebhooksList', function() {
      it('should call v1WebhooksList successfully', function(done) {
        //uncomment below and update the code to test v1WebhooksList
        //instance.v1WebhooksList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1WebhooksRetrieve', function() {
      it('should call v1WebhooksRetrieve successfully', function(done) {
        //uncomment below and update the code to test v1WebhooksRetrieve
        //instance.v1WebhooksRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1WebhooksUpdate', function() {
      it('should call v1WebhooksUpdate successfully', function(done) {
        //uncomment below and update the code to test v1WebhooksUpdate
        //instance.v1WebhooksUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
