/*
 * WaaS OpenAPI Documentation
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain struct for CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain
type CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain struct {
	HasNext bool `json:"has_next"`
	Items []Openweb3IoWaasAppWaasOpenapiServerApiDtosChain `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

// NewCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain instantiates a new CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain(hasNext bool, items []Openweb3IoWaasAppWaasOpenapiServerApiDtosChain) *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain {
	this := CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain{}
	this.HasNext = hasNext
	this.Items = items
	return &this
}

// NewCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChainWithDefaults instantiates a new CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChainWithDefaults() *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain {
	this := CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain{}
	return &this
}

// GetHasNext returns the HasNext field value
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetHasNext() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetHasNextOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.HasNext, true
}

// SetHasNext sets field value
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) SetHasNext(v bool) {
	o.HasNext = v
}

// GetItems returns the Items field value
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetItems() []Openweb3IoWaasAppWaasOpenapiServerApiDtosChain {
	if o == nil {
		var ret []Openweb3IoWaasAppWaasOpenapiServerApiDtosChain
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetItemsOk() (*[]Openweb3IoWaasAppWaasOpenapiServerApiDtosChain, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) SetItems(v []Openweb3IoWaasAppWaasOpenapiServerApiDtosChain) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetNextCursor() string {
	if o == nil || o.NextCursor == nil {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetNextCursorOk() (*string, bool) {
	if o == nil || o.NextCursor == nil {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) HasNextCursor() bool {
	if o != nil && o.NextCursor != nil {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetPrevCursor returns the PrevCursor field value if set, zero value otherwise.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetPrevCursor() string {
	if o == nil || o.PrevCursor == nil {
		var ret string
		return ret
	}
	return *o.PrevCursor
}

// GetPrevCursorOk returns a tuple with the PrevCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) GetPrevCursorOk() (*string, bool) {
	if o == nil || o.PrevCursor == nil {
		return nil, false
	}
	return o.PrevCursor, true
}

// HasPrevCursor returns a boolean if a field has been set.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) HasPrevCursor() bool {
	if o != nil && o.PrevCursor != nil {
		return true
	}

	return false
}

// SetPrevCursor gets a reference to the given string and assigns it to the PrevCursor field.
func (o *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) SetPrevCursor(v string) {
	o.PrevCursor = &v
}

func (o CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["has_next"] = o.HasNext
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if o.NextCursor != nil {
		toSerialize["next_cursor"] = o.NextCursor
	}
	if o.PrevCursor != nil {
		toSerialize["prev_cursor"] = o.PrevCursor
	}
	return json.Marshal(toSerialize)
}

type NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain struct {
	value *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain
	isSet bool
}

func (v NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) Get() *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain {
	return v.value
}

func (v *NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) Set(val *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain(val *CursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) *NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain {
	return &NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain{value: val, isSet: true}
}

func (v NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPageOpenweb3IoWaasAppWaasOpenapiServerApiDtosChain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


