/*
WaaS OpenAPI Documentation

This is a WaaS OpenAPI Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidateAddressesReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateAddressesReply{}

// ValidateAddressesReply struct for ValidateAddressesReply
type ValidateAddressesReply struct {
	// Address validity items
	Items []AddressValidityItem `json:"items"`
}

type _ValidateAddressesReply ValidateAddressesReply

// NewValidateAddressesReply instantiates a new ValidateAddressesReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateAddressesReply(items []AddressValidityItem) *ValidateAddressesReply {
	this := ValidateAddressesReply{}
	this.Items = items
	return &this
}

// NewValidateAddressesReplyWithDefaults instantiates a new ValidateAddressesReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateAddressesReplyWithDefaults() *ValidateAddressesReply {
	this := ValidateAddressesReply{}
	return &this
}

// GetItems returns the Items field value
func (o *ValidateAddressesReply) GetItems() []AddressValidityItem {
	if o == nil {
		var ret []AddressValidityItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ValidateAddressesReply) GetItemsOk() ([]AddressValidityItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ValidateAddressesReply) SetItems(v []AddressValidityItem) {
	o.Items = v
}

func (o ValidateAddressesReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateAddressesReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *ValidateAddressesReply) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateAddressesReply := _ValidateAddressesReply{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateAddressesReply)

	if err != nil {
		return err
	}

	*o = ValidateAddressesReply(varValidateAddressesReply)

	return err
}

type NullableValidateAddressesReply struct {
	value *ValidateAddressesReply
	isSet bool
}

func (v NullableValidateAddressesReply) Get() *ValidateAddressesReply {
	return v.value
}

func (v *NullableValidateAddressesReply) Set(val *ValidateAddressesReply) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateAddressesReply) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateAddressesReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateAddressesReply(val *ValidateAddressesReply) *NullableValidateAddressesReply {
	return &NullableValidateAddressesReply{value: val, isSet: true}
}

func (v NullableValidateAddressesReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateAddressesReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


