/*
 * WaaS OpenAPI Documentation
 *
 * This is a WaaS OpenAPI Server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransferDestinationAddress struct for TransferDestinationAddress
type TransferDestinationAddress struct {
	// Address
	Address string `json:"address"`
}

// NewTransferDestinationAddress instantiates a new TransferDestinationAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferDestinationAddress(address string) *TransferDestinationAddress {
	this := TransferDestinationAddress{}
	this.Address = address
	return &this
}

// NewTransferDestinationAddressWithDefaults instantiates a new TransferDestinationAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferDestinationAddressWithDefaults() *TransferDestinationAddress {
	this := TransferDestinationAddress{}
	return &this
}

// GetAddress returns the Address field value
func (o *TransferDestinationAddress) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *TransferDestinationAddress) GetAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *TransferDestinationAddress) SetAddress(v string) {
	o.Address = v
}

func (o TransferDestinationAddress) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullableTransferDestinationAddress struct {
	value *TransferDestinationAddress
	isSet bool
}

func (v NullableTransferDestinationAddress) Get() *TransferDestinationAddress {
	return v.value
}

func (v *NullableTransferDestinationAddress) Set(val *TransferDestinationAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferDestinationAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferDestinationAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferDestinationAddress(val *TransferDestinationAddress) *NullableTransferDestinationAddress {
	return &NullableTransferDestinationAddress{value: val, isSet: true}
}

func (v NullableTransferDestinationAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferDestinationAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


