/*
 * WaaS OpenAPI Documentation
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EstimateFeeRequest struct for EstimateFeeRequest
type EstimateFeeRequest struct {
	// Amount
	Amount string `json:"amount"`
	// Contract address
	ContractAddress *string `json:"contract_address,omitempty"`
	// Extra
	Extra *string `json:"extra,omitempty"`
	// From address
	FromAddress string `json:"from_address"`
	// Memo
	Memo *string `json:"memo,omitempty"`
	// To address
	ToAddress string `json:"to_address"`
	// Token ID
	TokenId string `json:"token_id"`
}

// NewEstimateFeeRequest instantiates a new EstimateFeeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateFeeRequest(amount string, fromAddress string, toAddress string, tokenId string) *EstimateFeeRequest {
	this := EstimateFeeRequest{}
	this.Amount = amount
	this.FromAddress = fromAddress
	this.ToAddress = toAddress
	this.TokenId = tokenId
	return &this
}

// NewEstimateFeeRequestWithDefaults instantiates a new EstimateFeeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateFeeRequestWithDefaults() *EstimateFeeRequest {
	this := EstimateFeeRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *EstimateFeeRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *EstimateFeeRequest) SetAmount(v string) {
	o.Amount = v
}

// GetContractAddress returns the ContractAddress field value if set, zero value otherwise.
func (o *EstimateFeeRequest) GetContractAddress() string {
	if o == nil || o.ContractAddress == nil {
		var ret string
		return ret
	}
	return *o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetContractAddressOk() (*string, bool) {
	if o == nil || o.ContractAddress == nil {
		return nil, false
	}
	return o.ContractAddress, true
}

// HasContractAddress returns a boolean if a field has been set.
func (o *EstimateFeeRequest) HasContractAddress() bool {
	if o != nil && o.ContractAddress != nil {
		return true
	}

	return false
}

// SetContractAddress gets a reference to the given string and assigns it to the ContractAddress field.
func (o *EstimateFeeRequest) SetContractAddress(v string) {
	o.ContractAddress = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *EstimateFeeRequest) GetExtra() string {
	if o == nil || o.Extra == nil {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetExtraOk() (*string, bool) {
	if o == nil || o.Extra == nil {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *EstimateFeeRequest) HasExtra() bool {
	if o != nil && o.Extra != nil {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *EstimateFeeRequest) SetExtra(v string) {
	o.Extra = &v
}

// GetFromAddress returns the FromAddress field value
func (o *EstimateFeeRequest) GetFromAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromAddress
}

// GetFromAddressOk returns a tuple with the FromAddress field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetFromAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAddress, true
}

// SetFromAddress sets field value
func (o *EstimateFeeRequest) SetFromAddress(v string) {
	o.FromAddress = v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *EstimateFeeRequest) GetMemo() string {
	if o == nil || o.Memo == nil {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetMemoOk() (*string, bool) {
	if o == nil || o.Memo == nil {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *EstimateFeeRequest) HasMemo() bool {
	if o != nil && o.Memo != nil {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *EstimateFeeRequest) SetMemo(v string) {
	o.Memo = &v
}

// GetToAddress returns the ToAddress field value
func (o *EstimateFeeRequest) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *EstimateFeeRequest) SetToAddress(v string) {
	o.ToAddress = v
}

// GetTokenId returns the TokenId field value
func (o *EstimateFeeRequest) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *EstimateFeeRequest) SetTokenId(v string) {
	o.TokenId = v
}

func (o EstimateFeeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if o.ContractAddress != nil {
		toSerialize["contract_address"] = o.ContractAddress
	}
	if o.Extra != nil {
		toSerialize["extra"] = o.Extra
	}
	if true {
		toSerialize["from_address"] = o.FromAddress
	}
	if o.Memo != nil {
		toSerialize["memo"] = o.Memo
	}
	if true {
		toSerialize["to_address"] = o.ToAddress
	}
	if true {
		toSerialize["token_id"] = o.TokenId
	}
	return json.Marshal(toSerialize)
}

type NullableEstimateFeeRequest struct {
	value *EstimateFeeRequest
	isSet bool
}

func (v NullableEstimateFeeRequest) Get() *EstimateFeeRequest {
	return v.value
}

func (v *NullableEstimateFeeRequest) Set(val *EstimateFeeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateFeeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateFeeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateFeeRequest(val *EstimateFeeRequest) *NullableEstimateFeeRequest {
	return &NullableEstimateFeeRequest{value: val, isSet: true}
}

func (v NullableEstimateFeeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateFeeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
