/*
WaaS OpenAPI Documentation

This is a WaaS OpenAPI Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTransferResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransferResponse{}

// CreateTransferResponse struct for CreateTransferResponse
type CreateTransferResponse struct {
	// Transaction status
	Status string `json:"status"`
	// Transaction ID
	TransactionId string `json:"transaction_id"`
}

type _CreateTransferResponse CreateTransferResponse

// NewCreateTransferResponse instantiates a new CreateTransferResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransferResponse(status string, transactionId string) *CreateTransferResponse {
	this := CreateTransferResponse{}
	this.Status = status
	this.TransactionId = transactionId
	return &this
}

// NewCreateTransferResponseWithDefaults instantiates a new CreateTransferResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransferResponseWithDefaults() *CreateTransferResponse {
	this := CreateTransferResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateTransferResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateTransferResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateTransferResponse) SetStatus(v string) {
	o.Status = v
}

// GetTransactionId returns the TransactionId field value
func (o *CreateTransferResponse) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *CreateTransferResponse) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *CreateTransferResponse) SetTransactionId(v string) {
	o.TransactionId = v
}

func (o CreateTransferResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTransferResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["transaction_id"] = o.TransactionId
	return toSerialize, nil
}

func (o *CreateTransferResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"transaction_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTransferResponse := _CreateTransferResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTransferResponse)

	if err != nil {
		return err
	}

	*o = CreateTransferResponse(varCreateTransferResponse)

	return err
}

type NullableCreateTransferResponse struct {
	value *CreateTransferResponse
	isSet bool
}

func (v NullableCreateTransferResponse) Get() *CreateTransferResponse {
	return v.value
}

func (v *NullableCreateTransferResponse) Set(val *CreateTransferResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTransferResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTransferResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTransferResponse(val *CreateTransferResponse) *NullableCreateTransferResponse {
	return &NullableCreateTransferResponse{value: val, isSet: true}
}

func (v NullableCreateTransferResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTransferResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


