/*
WaaS OpenAPI Documentation

This is a WaaS OpenAPI Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CursorIteratorEventType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CursorIteratorEventType{}

// CursorIteratorEventType struct for CursorIteratorEventType
type CursorIteratorEventType struct {
	Done bool `json:"done"`
	HasNext bool `json:"has_next"`
	HasPrev bool `json:"has_prev"`
	Items []EventType `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

type _CursorIteratorEventType CursorIteratorEventType

// NewCursorIteratorEventType instantiates a new CursorIteratorEventType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorIteratorEventType(done bool, hasNext bool, hasPrev bool, items []EventType) *CursorIteratorEventType {
	this := CursorIteratorEventType{}
	this.Done = done
	this.HasNext = hasNext
	this.HasPrev = hasPrev
	this.Items = items
	return &this
}

// NewCursorIteratorEventTypeWithDefaults instantiates a new CursorIteratorEventType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorIteratorEventTypeWithDefaults() *CursorIteratorEventType {
	this := CursorIteratorEventType{}
	return &this
}

// GetDone returns the Done field value
func (o *CursorIteratorEventType) GetDone() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Done
}

// GetDoneOk returns a tuple with the Done field value
// and a boolean to check if the value has been set.
func (o *CursorIteratorEventType) GetDoneOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Done, true
}

// SetDone sets field value
func (o *CursorIteratorEventType) SetDone(v bool) {
	o.Done = v
}

// GetHasNext returns the HasNext field value
func (o *CursorIteratorEventType) GetHasNext() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
func (o *CursorIteratorEventType) GetHasNextOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNext, true
}

// SetHasNext sets field value
func (o *CursorIteratorEventType) SetHasNext(v bool) {
	o.HasNext = v
}

// GetHasPrev returns the HasPrev field value
func (o *CursorIteratorEventType) GetHasPrev() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasPrev
}

// GetHasPrevOk returns a tuple with the HasPrev field value
// and a boolean to check if the value has been set.
func (o *CursorIteratorEventType) GetHasPrevOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasPrev, true
}

// SetHasPrev sets field value
func (o *CursorIteratorEventType) SetHasPrev(v bool) {
	o.HasPrev = v
}

// GetItems returns the Items field value
func (o *CursorIteratorEventType) GetItems() []EventType {
	if o == nil {
		var ret []EventType
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CursorIteratorEventType) GetItemsOk() ([]EventType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CursorIteratorEventType) SetItems(v []EventType) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *CursorIteratorEventType) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorIteratorEventType) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CursorIteratorEventType) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *CursorIteratorEventType) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetPrevCursor returns the PrevCursor field value if set, zero value otherwise.
func (o *CursorIteratorEventType) GetPrevCursor() string {
	if o == nil || IsNil(o.PrevCursor) {
		var ret string
		return ret
	}
	return *o.PrevCursor
}

// GetPrevCursorOk returns a tuple with the PrevCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorIteratorEventType) GetPrevCursorOk() (*string, bool) {
	if o == nil || IsNil(o.PrevCursor) {
		return nil, false
	}
	return o.PrevCursor, true
}

// HasPrevCursor returns a boolean if a field has been set.
func (o *CursorIteratorEventType) HasPrevCursor() bool {
	if o != nil && !IsNil(o.PrevCursor) {
		return true
	}

	return false
}

// SetPrevCursor gets a reference to the given string and assigns it to the PrevCursor field.
func (o *CursorIteratorEventType) SetPrevCursor(v string) {
	o.PrevCursor = &v
}

func (o CursorIteratorEventType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CursorIteratorEventType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["done"] = o.Done
	toSerialize["has_next"] = o.HasNext
	toSerialize["has_prev"] = o.HasPrev
	toSerialize["items"] = o.Items
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	if !IsNil(o.PrevCursor) {
		toSerialize["prev_cursor"] = o.PrevCursor
	}
	return toSerialize, nil
}

func (o *CursorIteratorEventType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"done",
		"has_next",
		"has_prev",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCursorIteratorEventType := _CursorIteratorEventType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCursorIteratorEventType)

	if err != nil {
		return err
	}

	*o = CursorIteratorEventType(varCursorIteratorEventType)

	return err
}

type NullableCursorIteratorEventType struct {
	value *CursorIteratorEventType
	isSet bool
}

func (v NullableCursorIteratorEventType) Get() *CursorIteratorEventType {
	return v.value
}

func (v *NullableCursorIteratorEventType) Set(val *CursorIteratorEventType) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorIteratorEventType) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorIteratorEventType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorIteratorEventType(val *CursorIteratorEventType) *NullableCursorIteratorEventType {
	return &NullableCursorIteratorEventType{value: val, isSet: true}
}

func (v NullableCursorIteratorEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorIteratorEventType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


