/*
 * WaaS OpenAPI Documentation
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateTokenRequest struct for UpdateTokenRequest
type UpdateTokenRequest struct {
	// Token ID
	Id *string `json:"id,omitempty"`
	// Token name
	Name *string `json:"name,omitempty"`
	// Unique ID
	Uid *string `json:"uid,omitempty"`
}

// NewUpdateTokenRequest instantiates a new UpdateTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTokenRequest() *UpdateTokenRequest {
	this := UpdateTokenRequest{}
	return &this
}

// NewUpdateTokenRequestWithDefaults instantiates a new UpdateTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTokenRequestWithDefaults() *UpdateTokenRequest {
	this := UpdateTokenRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdateTokenRequest) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTokenRequest) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateTokenRequest) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UpdateTokenRequest) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateTokenRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTokenRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateTokenRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateTokenRequest) SetName(v string) {
	o.Name = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *UpdateTokenRequest) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTokenRequest) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *UpdateTokenRequest) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *UpdateTokenRequest) SetUid(v string) {
	o.Uid = &v
}

func (o UpdateTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateTokenRequest struct {
	value *UpdateTokenRequest
	isSet bool
}

func (v NullableUpdateTokenRequest) Get() *UpdateTokenRequest {
	return v.value
}

func (v *NullableUpdateTokenRequest) Set(val *UpdateTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTokenRequest(val *UpdateTokenRequest) *NullableUpdateTokenRequest {
	return &NullableUpdateTokenRequest{value: val, isSet: true}
}

func (v NullableUpdateTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


