/*
 * WaaS OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.waas.internal.api;

import io.openweb3.waas.internal.ApiException;
import io.openweb3.waas.models.CreateTokenRequest;
import io.openweb3.waas.models.CursorPageToken;
import io.openweb3.waas.models.Error;
import io.openweb3.waas.models.Token;
import io.openweb3.waas.models.UpdateTokenRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokensApi
 */
@Ignore
public class TokensApiTest {

    private final TokensApi api = new TokensApi();

    
    /**
     * Create token
     *
     * Create a tokens.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1TokensCreateTest() throws ApiException {
        CreateTokenRequest createTokenRequest = null;
        Token response = api.v1TokensCreate(createTokenRequest);

        // TODO: test validations
    }
    
    /**
     * List tokens
     *
     * Retrieve a list of all tokens.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1TokensListTest() throws ApiException {
        String cursor = null;
        Integer limit = null;
        CursorPageToken response = api.v1TokensList(cursor, limit);

        // TODO: test validations
    }
    
    /**
     * Get Token
     *
     * Get token info by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1TokensRetrieveTest() throws ApiException {
        String tokenId = null;
        Token response = api.v1TokensRetrieve(tokenId);

        // TODO: test validations
    }
    
    /**
     * Update token
     *
     * Update a tokens.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1TokensUpdateTest() throws ApiException {
        String tokenId = null;
        UpdateTokenRequest updateTokenRequest = null;
        Token response = api.v1TokensUpdate(tokenId, updateTokenRequest);

        // TODO: test validations
    }
    
}
